# Generated by Django 4.0.4 on 2022-06-07 18:23

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80, verbose_name='ФИО')),
                ('position', models.CharField(max_length=80, verbose_name='Должность')),
                ('employment_date', models.DateField(verbose_name='Дата приема')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('chief', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Руководитель', to='catalog.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
