# Generated by Django 4.0.4 on 2022-06-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_employee_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='parent',
            new_name='chief',
        ),
    ]
