# Generated by Django 4.0.4 on 2022-06-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_parent_employee_chief'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='chief',
            new_name='parent',
        ),
    ]
